export enum APIRoutes {
  RootGet = "/",
  HelloGet = "/hello",
  Users = "/users",
  AuthLoginPost = "/auth/login",
  AuthSignupPost = "/auth/signup",
  AuthChangePasswordPatch = "/auth/change-password",
  AuthLogoutPost = "/auth/logout",
  AuthSessionsGet = "/auth/sessions",
  Evaluations = "/evaluations",
  NotificationsEvaluationNotificationPost = "/notifications/evaluation-notification",
  NotificationsEvaluationCompletePost = "/notifications/evaluation-complete",
  NotificationsEvaluationReminderPost = "/notifications/evaluation-reminder",
  AdminUsers = "/admin/users",
  AdminEvaluationsStatsGet = "/admin/evaluations/stats",
  AdminSettingsDeadlinesPost = "/admin/settings/deadlines",
  AdminReportsPerformanceGet = "/admin/reports/performance",
}
