export enum APIRoutes {
  Users = "/users",
  AuthLogin = "/auth/login",
  AuthSignup = "/auth/signup",
  AuthChangePassword = "/auth/change-password",
  AuthLogout = "/auth/logout",
  AuthSessions = "/auth/sessions",
  Evaluations = "/evaluations",
  NotificationsEvaluationNotification = "/notifications/evaluation-notification",
  NotificationsEvaluationComplete = "/notifications/evaluation-complete",
  NotificationsEvaluationReminder = "/notifications/evaluation-reminder",
  AdminUsers = "/admin/users",
  AdminEvaluationsStats = "/admin/evaluations/stats",
  AdminSettingsDeadlines = "/admin/settings/deadlines",
  AdminReportsPerformance = "/admin/reports/performance",
}
